// Auto-generated by swagger-to-ddd
// This file is overwritten on each generation run for the specified module.
// Manual changes to other modules might be lost.
const BASE_URL = 'https://petstore.swagger.io/v2';

export const endpoints = {
  PET: {
    uploadFile: (petId) => {
      return `${BASE_URL}/pet/${petId}/uploadImage`;
    },
    add: () => {
      return `${BASE_URL}/pet`;
    },
    update: () => {
      return `${BASE_URL}/pet`;
    },
    findsByStatus: (status) => {
      return `${BASE_URL}/pet/findByStatus?status=${status}`;
    },
    findsByTags: (tags) => {
      return `${BASE_URL}/pet/findByTags?tags=${tags}`;
    },
    getById: (petId) => {
      return `${BASE_URL}/pet/${petId}`;
    },
    updateWithForm: (petId) => {
      return `${BASE_URL}/pet/${petId}`;
    },
    delete: (petId) => {
      return `${BASE_URL}/pet/${petId}`;
    },
  },
};
