// Auto-generated by swagger-to-ddd
// This file is overwritten on each generation run for the specified module.
// Manual changes to other modules might be lost.
const BASE_URL = 'https://petstore.swagger.io/v2';

export const endpoints = {
  PET: {
    UPLOAD_FILE: (petId: number) => {
      return `${BASE_URL}/pet/${petId}/uploadImage`;
    },
    ADD: () => {
      return `${BASE_URL}/pet`;
    },
    UPDATE: () => {
      return `${BASE_URL}/pet`;
    },
    FINDS_BY_STATUS: (status: Array<'available' | 'pending' | 'sold'>) => {
      return `${BASE_URL}/pet/findByStatus`;
    },
    FINDS_BY_TAGS: (tags: Array<string>) => {
      return `${BASE_URL}/pet/findByTags`;
    },
    GET_BY_ID: (petId: number) => {
      return `${BASE_URL}/pet/${petId}`;
    },
    UPDATE_WITH_FORM: (petId: number) => {
      return `${BASE_URL}/pet/${petId}`;
    },
    DELETE: (petId: number) => {
      return `${BASE_URL}/pet/${petId}`;
    },
  },
};
