// Auto-generated by swagger-to-ddd
// This file is overwritten on each generation run for the specified module.
// Manual changes to other modules might be lost.
const BASE_URL = 'https://petstore.swagger.io/v2';

export const endpoints = {
  PET: {
    POST_PET_PETID_UPLOAD_IMAGE: (petId: number) => {
      return `${BASE_URL}/pet/${petId}/uploadImage`;
    },
    POST_PET: () => {
      return `${BASE_URL}/pet`;
    },
    PUT_PET: () => {
      return `${BASE_URL}/pet`;
    },
    GET_PET_FIND_BY_STATUS: (
      status: Array<'available' | 'pending' | 'sold'>,
    ) => {
      return `${BASE_URL}/pet/findByStatus`;
    },
    GET_PET_FIND_BY_TAGS: (tags: Array<string>) => {
      return `${BASE_URL}/pet/findByTags`;
    },
    GET_PET_PETID: (petId: number) => {
      return `${BASE_URL}/pet/${petId}`;
    },
    POST_PET_PETID: (petId: number) => {
      return `${BASE_URL}/pet/${petId}`;
    },
    DELETE_PET_PETID: (petId: number) => {
      return `${BASE_URL}/pet/${petId}`;
    },
  },
};
